config {
  // module configuration
  modules {
    // List of available modules
    available = [
      {
        id = "TelemetryModule"
        class = "me.code4me.services.modules.telemetry.TelemetryModule"
        name = "Telemetry Module"
        type = "telemetry"
        description = "Module for collecting telemetry data"
        enabled = true
      }
      // Add more modules as needed
    ]

    // Module categories
    categories = {
      telemetry = {
        path = "me.code4me.services.modules.telemetry"
        description = "Modules for telemetry collection"
      }
      context = {
        path = "me.code4me.services.modules.context"
        description = "Modules for context retrieval"
      }
      aggregators = {
        path = "me.code4me.services.modules.aggregators"
        description = "Modules for data aggregation"
      }
    }
  }
  // Server Settings
  server {
    host = "http://127.0.0.1"
    port = 8000
    contextPath = ""
    timeout = 5000
  }
  // Authentication Settings
  auth {
    google {
      clientId = "67736337656-un249ihklv5i93n033i1v46q12bfv5g2.apps.googleusercontent.com"
    }
  }
}
